[package]
name = "arkecosystem-crypto"
version = "0.0.1"
authors = ["Juan A. Martín <dev@jaml.pro>"]
description = "A Rust cryptography implementation for the Ark Ecosystem"
license = "MIT"

[lib]
name = "arkecosystem_crypto"
path = "src/lib.rs"

[dependencies]
bitcoin = "0.14.0"
failure = "0.1.2"
serde_json = "1.0.26"
lazy_static = "1.1.0"
chrono = "0.4.6"
