[package]
name = "arkecosystem-crypto"
version = "0.0.1"
authors = ["Juan A. Martín <dev@jaml.pro>"]
description = "A Rust cryptography implementation for the Ark Ecosystem"
license = "MIT"

[dependencies]
