version: 2
jobs:
  build-beta:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Cargo build and test
          command: |
            rustup update
            rustup install beta
            rustup run beta cargo build
            rustup run beta cargo test
      - run:
          name: Clippy
          command: |
            rustup component add --toolchain beta clippy
            rustup run beta cargo clippy --all-targets --all-features -- -D warnings
      - run:
          name: rustfmt
          command: |
            rustup component add --toolchain beta rustfmt
            rustup run beta cargo fmt -- --check
  build-stable:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Cargo build and test
          command: |
            cargo clean
            cargo build
            cargo test
      - run:
          name: Clippy
          command: |
            rustup update
            rustup install stable
            # Clippy is no longer available via crates.io
            rustup component add --toolchain stable clippy
            rustup run stable cargo clippy --all-targets --all-features -- -D warnings
      - run:
          name: rustfmt
          command: |
            rustup component add --toolchain stable rustfmt
            rustup run stable cargo fmt -- --check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-beta
      - build-stable
