name: Test

on:
    push:
        branches:
            - '**'
    pull_request:
        types: [opened]

jobs:
  beta:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update
      run: rustup update
    - name: Install beta
      run: rustup install beta
    - name: Build
      run: rustup run beta cargo build --verbose
    - name: Run tests
      run: rustup run beta cargo test --verbose
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

  stable:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Clean
      run: cargo clean --verbose
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
